# Generated by Django 3.2.4 on 2021-08-04 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtoadmin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 20, 38, 17, 590403)),
        ),
    ]
